name: DevSecOps Spring Boot Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write   # required for CodeQL

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔐 Secret Scanning
      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@v3
        with:
          scan: true

      # 🔍 CodeQL Init (SAST - GitHub native)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      # ☕ Build Project
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # 🔍 SonarQube Scan (SAST)
      - name: SonarQube Scan
        run: mvn sonar:sonar \
          -Dsonar.projectKey=springboot-devsecops \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=sqp_88f62f66f0534a2b692bba637f39b40ff4d857c3 \
          -Dsonar.qualitygate.wait=true

      # 🔍 Dependency Scanning (SCA)
      - name: Snyk Scan
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test

      # 🐳 Build Docker Image
      - name: Build Docker Image
        run: docker build -t springboot-devsecops .

      # 🐳 Container Scan
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: springboot-devsecops
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      # 🔍 CodeQL Analysis (must be after build)
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # 🚀 Deploy (Mock)
      - name: Deploy
        run: echo "Deployment successful"